{"name": "Ошибка 400 Bad Request при попытке сделать пустой заказ неавторизованным пользователем", "status": "broken", "statusDetails": {"message": "NameError: name 'burger_api' is not defined", "trace": "self = <tests.test_create_order.TestCreateOrder object at 0x000001DA710E3260>\n\n    @allure.title(\"Ошибка 400 Bad Request при попытке сделать пустой заказ неавторизованным пользователем\")\n    @allure.description(\n        \"При попытке сделать пустой заказ неавторизованным пользователем возвращается ошибка 400 Bad Request\")\n    def test_create_order_without_burger_not_auth_user_fail(self):\n>       create_response = burger_api.create_new_order(None, None)\nE       NameError: name 'burger_api' is not defined\n\ntests\\test_create_order.py:37: NameError"}, "description": "При попытке сделать пустой заказ неавторизованным пользователем возвращается ошибка 400 Bad Request", "start": 1737281394948, "stop": 1737281394948, "uuid": "d655d714-c6d7-4098-b5ea-5e3152ff4bb8", "historyId": "66e61c0a68623a6b501db8258dfdb75e", "testCaseId": "66e61c0a68623a6b501db8258dfdb75e", "fullName": "tests.test_create_order.TestCreateOrder#test_create_order_without_burger_not_auth_user_fail", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_create_order"}, {"name": "subSuite", "value": "TestCreateOrder"}, {"name": "host", "value": "01ms32"}, {"name": "thread", "value": "10576-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_create_order"}]}