{"name": "Ошибка 500 Internal Server Error при попытке сделать заказ авторизованным пользователем с невалидным хешем ингредиента", "status": "passed", "description": "При попытке сделать заказ авторизованным пользователем ингредиенты с невалидным хешем, возвращается ошибка 500 Internal Server Error", "steps": [{"name": "Создание заказа", "status": "passed", "parameters": [{"name": "headers", "value": "{'Authorization': 'Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3OGNkNDUwOWVkMjgwMDAxYjU1Mjk4YSIsImlhdCI6MTczNzI4MjY0MCwiZXhwIjoxNzM3MjgzODQwfQ.BTmzVAxIaqCi8MiQ50nvgFFHI3w1UuH6ztrx_rjwnIk'}"}, {"name": "ingredients", "value": "{'ingredients': ['777kit555', '34ter434']}"}], "start": 1737282641253, "stop": 1737282641308}], "start": 1737282641253, "stop": 1737282641309, "uuid": "cf2f8187-1322-483d-9966-8e4bbe4b0d3b", "historyId": "9eeb56360e08e7affc6efa227e1428c6", "testCaseId": "9eeb56360e08e7affc6efa227e1428c6", "fullName": "tests.test_create_order.TestCreateOrder#test_create_order_auth_user_wrong_hash_fail", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_create_order"}, {"name": "subSuite", "value": "TestCreateOrder"}, {"name": "host", "value": "01ms32"}, {"name": "thread", "value": "3692-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_create_order"}]}